### ISSUE TITLE
Add support for multi-chain balances

### ISSUE THREAD

**Issue by 0xJem** [OlympusDAO/olympus-protocol-metrics-subgraph#17]

**Comment by o0j4yj4y0o** [comment]
@0xJem and I spoke about this and the Graph Decentralized doesn't have cross chain support yet.  Will need to find out when that's available to advance this task.

**Comment by 0xJem** [comment]
Graph Protocol is announcing the next chain to be available on the decentralised network in 1-2 days, so this may be possible
