### ISSUE TITLE
Add additional assets to Liquid Backing and apply weighting to assets where we hold high supply

### ISSUE THREAD

**Issue by o0j4yj4y0o** [OlympusDAO/olympus-protocol-metrics-subgraph#186]
Jem,

The Treasury Team has engaged with Policy on adding several assets that we see are missing from the Liquid Backing Graph and we feel should be added.  **Policy would like to see what Liquid Backing would be produced with these changes before they are pushed to the production site as they could dramatically impact a future RBS min target price.**

Add these assets to Liquid Backing:

```
wBTC on ETH - 100% - Current spot price $446,508.68 
Naked USDC on ETH - 100% - Current spot price $249,917.85
Naked ETH on ETH - 100% - Current spot price $119,421.82
```
Apply weighted values to the following assets where Treasury has deemed that we hold so much of the circulating supply, the spot market value is not conservatives enough to all be added to liquid backing.

The formula used to derive these values was to place them against their deepest liquidity counter party asset and determine what the spot slippage was.  50% of that slippage value was taken and subtracted from the spot value creating a weighted valuation that we feel is more conservative.

```
JONES - 83% of Market Value towards liquid backing
KLIMA - 85% of Market Value towards liquid backing
rlBTRFLY - 89% of Market Value towards liquid backing
VSTA - 77% of Market Value towards liquid backing
BOND - 77% of Market Value towards liquid backing
```

If these two changes can be added and what the new liquid backing would be can be shared.  Treasury and Policy will review and then determine how to push to the front end prod site.

**Comment by 0xJem** [comment]
> wBTC on ETH - 100% - Current spot price $446,508.68 
> Naked USDC on ETH - 100% - Current spot price $249,917.85

These both are already considered in liquid backing. The only assets excluded are OHM and anything locked for a long period (e.g. veFXS).

> Naked ETH on ETH - 100% - Current spot price $119,421.82

ETH can't be indexed in a subgraph (ERC20s only). I'd suggest wrapping this ETH if you want it considered in market value and liquid backing.

Roger on the weighted valuation.

**Comment by 0xJem** [comment]
Do you want the weighted valuation to be retroactive, or to apply from now onwards?

**Comment by o0j4yj4y0o** [comment]
I think now, onward would be fine.

As for the liquid backing considerations, it appears that wBTC doesn't show up on the Liquid Backing Portion of the Treasury Dash.  Is that to say it's in the LB calculation but just not there.

Roger on ETH needed to be wETH.  I will talk to the team about that.

Thanks!
