### ISSUE TITLE
Add OHM/DAI LP to The Graph for AURA

### ISSUE THREAD

**Issue by o0j4yj4y0o** [OlympusDAO/olympus-protocol-metrics-subgraph#196]
OHM/DAI LP has been staked in AURA.  Needs to be added to The Graph and to ensure the DAI side stays in LB.

**Comment by 0xJem** [comment]
<img width="378" alt="Screenshot 2023-04-06 at 11 22 10 AM" src="https://user-images.githubusercontent.com/91760036/230304126-e6961f6c-ebe2-48f4-8815-63e2dc312706.png">

It seems that I added support for this earlier. 😎
