### ISSUE TITLE
Add ARB to the Treasury Subgraph

### ISSUE THREAD

**Issue by o0j4yj4y0o** [OlympusDAO/olympus-protocol-metrics-subgraph#203]
![image](https://user-images.githubusercontent.com/103340425/234151571-97684b20-68df-46c8-a154-d9a10062f7fc.png)

We have received our ARB Distribution from the Arbitrum One Foundation so should be getting picked up in that allocator:

0x012bbf0481b97170577745d2167ee14f63e2ad4c

**Comment by 0xJem** [comment]
This was added some time back, FYI.
