### ISSUE TITLE
Unlocked vlCVX is missing in treasury assets

### ISSUE THREAD

**Issue by 0xJem** [OlympusDAO/olympus-protocol-metrics-subgraph#48]
The volatile assets dropped by $6m from 3rd August 2022 to 4th August 2022, coinciding with the unlocking of vlCVX.

Discussion here: https://discord.com/channels/838651642190495804/928504031960256542/1004697028787445880

Cause:
- We've been treating vlCVX as a standard ERC20 token and getting the balance using `balanceOf`. This reports the **locked** balance, but does not report the unlocked and un-withdrawn balance.
- `lockedBalanceOf` returns the unlocked + locked balance, or alternatively, we can call `lockedBalances` and get a struct with total/unlockable/locked

TBC whether to differentiate between locked and unlocked balances (e.g. "vlCVX (Locked)" and "vlCVX (Unlocked)")

**Comment by bg1156** [comment]
appreciate teams efforts...thanks

**Comment by o0j4yj4y0o** [comment]
@0xJem

json wanted to change the displayed string for these to be a little more clear.  Can we change the following:

Convex - Vote-Locked - Unlocked (vlCVX)  >> Convex - Unlocked (vlCVX)
Convex - Vote-Locked (vlCVX) >> Convex - Vote-Locked (vlCVX)

Thanks!
