### ISSUE TITLE
Implement CSV output from GraphQL

### ISSUE THREAD

**Issue by 0xJem** [OlympusDAO/olympus-protocol-metrics-subgraph#7]
Policy/treasury team would like to get the output in a CSV format in order to make it easier to analyse.

The GraphQL output or JSON could be easily converted into a CSV format, however an apparent limitation of the subgraph library means that we can't return custom types from a metric. The closest option is an array of strings (which is what we do). This isn't valid JSON, so conversion doesn't work without manual steps.

**Comment by cvauclair** [comment]
Gm ser! I suggest you take a look at Subgrounds for solving this issue. This is exactly what we (the Playgrounds team) implemented for the Olympus Pro team a few months ago.

https://github.com/0xPlaygrounds/olympus-pro-subgrounds

**Comment by 0xJem** [comment]
Thanks for the heads up!

**Comment by 0xJem** [comment]
The Playgrounds example is good if there's a developer that is familiar with using Python, but sadly won't be easy enough for the intended audience (policy).

I've put together content in the README (and a gif) to demonstrate how to do this, instead.
